<div class="menucont">
  <div class="menuentry">
  	<a href="<?php echo $baseURL; ?>">Home</a>
 	</div>
  <div class="menuentry">
  	<a href="<?php echo $baseURL . '/personalities/'; ?>">Personalities</a>
 	</div>
 	<div class="menuentry">
 		<a href="<?php echo $baseURL . '/programming/'; ?>">Programming</a>
 	</div>
 	<div class="menuentry">
 		<a href="<?php echo $baseURL . '/sports/'; ?>">Sports</a>
 	</div>
 	<div class="menuentry">
 		<a href="<?php echo $baseURL . '/contacts/'; ?>">Contact</a>
 	</div>
</div>
